Feat : review repo and cicd for public access
MOV-AI/containers-ign-simulator pull request #11
Opened 2022-04-14 16:26 UTC by AlexFernandes-MOVAI

Feat : review repo and cicd for public access

### Content
- Fixing DP-563
- Had to update version of `ignition-fortress=1.0.2-1~bionic` to `ignition-fortress=1.0.3-1~bionic` as the old one disappeared from repo
---
- [ ] Make sure you are opening from a **topic/feature/bugfix branch**
- [ ] Ensure that the PR title represents the desired changes
- [ ] Ensure that the PR description detail the desired changes
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

2022-04-14 17:06 UTC, MithunKinarullathil approved these changes

2022-04-21 15:54 UTC, FilipeAlmeida-Movai approved these changes

2022-04-22 13:31 UTC, MithunKinarullathil requested changes
Docker build on this branch is not working
![image](https://user-images.githubusercontent.com/51120171/164724255-7b8e0ff1-59b6-466d-932d-9c9eaac04ea3.png)

2022-04-22 13:34 UTC, AlexFernandes-MOVAI commented
> Docker build on this branch is not working ![image](https://user-images.githubusercontent.com/51120171/164724255-7b8e0ff1-59b6-466d-932d-9c9eaac04ea3.png)
you just miss a `docker login registry.aws.cloud.mov.ai`

2022-04-26 23:18 UTC, merged